app/main/__init__.py
#此处可以定义一个蓝本，导入视图view,导入model
from flask import Blueprint
main = Blueprint('main',__name__)
#注意顺序
from .import views,errors

app/main/views.py
# coding:utf-8
import json
import os
import hashlib
import re
from datetime import datetime
from flask import flash, render_template, redirect, url_for, request
from flask_login import login_user, login_required, logout_user, current_user
from sqlalchemy import desc
from app import db, mail
from app.mail import send_email
from app.main.form import LoginForm, RegistrationForm, EditProfileForm, ChangePassword, WorkForm, WorkFormEidt, \
    CourseForm
from . import main
from ..models import Courses, Houseworks, Students, States, Teamnumbers, Permission, ReadHistory, PicSave, EmailSender


@main.route("/homework/addCourses", methods=['POST', 'GET'])
@login_required
def addCourses():
    if current_user.is_admin():
        form = CourseForm()
        if form.validate_on_submit():
            tid = current_user.fk_tid
            course = Courses(id=form.id.data,
                             name=form.name.data,
                             fk_tid=tid)
            db.session.add(course)
            try:
                db.session.commit()
            except:
                db.session.rollback()
                flash('更新数据失败！')
            return redirect(url_for('main.info'))
        return render_template('/addcourses.html', form=form)
    else:
        return render_template('/404.html')


@main.route("/homework/addWork", methods=['POST', 'GET'])
@login_required
def addWork():
    if current_user.is_admin():
        form = WorkForm()
        tid = current_user.fk_tid
        form.courses.choices = [(c.id, c.name) for c in Courses.query.filter_by(fk_tid=tid).order_by('name')]
        if form.validate_on_submit():
            housework = Houseworks(fk_tid=tid, title=form.title.data,
                                   state=int(form.state.data),
                                   content=form.content.data,
                                   createdate=datetime.now(),
                                   fk_cid=form.courses.data)
            content = housework.content
            patten = re.compile("<img[^>]*>")
            src = patten.findall(content)
            print(src)
            srcnew = [i.replace(' ', '').replace('<imgsrc="', 'app').replace('"style="max-width:100%;">', '') for i in
                      src]
            db.session.add(housework)
            try:
                db.session.commit()
            except:
                db.session.rollback()
                flash('更新数据失败！')
            for i in srcnew:
                pic = PicSave.query.filter_by(path=i, fk_sid=current_user.id).first()
                if pic is not None:
                    pic.fk_workid = housework.id
                    print(housework.id)
                    db.session.add(pic)
                    try:
                        db.session.commit()
                    except:
                        db.session.rollback()
                        flash('更新数据失败！')
            delpic = PicSave.query.filter_by(fk_sid=current_user.id, fk_workid=None).all()
            for p in delpic:
                os.remove(p.path)
                db.session.delete(p)
                db.session.commit()
            cname = Courses.query.filter_by(id=housework.fk_cid).first().name
            sendto = EmailSender.query.filter_by(fk_tid=tid, isopen=True).all()
            print(sendto)

            for i in sendto:
                user = Students.query.filter_by(id=i.fk_sid).first()
                send_email(i.email, '来自' + i.fk_tid + '的' + cname + '(有新消息)', '/mail/mail', info=housework,user=user)
            return redirect(url_for('main.info'))
        return render_template('/addwork.html', form=form)
    else:
        return render_template('/404.html')


@main.route('/homework/changePassword', methods=['POST', 'GET'])
@login_required
def changePassword():
    form = ChangePassword()
    if form.validate_on_submit():
        user = Students.query.filter_by(id=current_user.id).first()
        if user.verify_password(form.ordinalPassword.data):
            user.password = form.password.data
            db.session.add(user)
            try:
                db.session.commit()
            except:
                db.session.rollback()
                flash('更新数据失败！')
            flash("修改成功")
        else:
            flash("原密码不匹配")
            return render_template('/changePassword.html', form=form)
        return redirect(url_for('main.profile'))
    return render_template('/changePassword.html', form=form)


@main.route('/homework/changeProfile', methods=['POST', 'GET'])
@login_required
def changeProfile():
    form = EditProfileForm()

    if form.validate_on_submit():
        user = Students.query.filter_by(id=current_user.id).first()
        if user.name == form.name.data and user.email == form.email.data:
            flash('个人信息没有发生改变')
        else:
            if user.name != form.name.data:
                user.name = form.name.data
            if user.email != form.email.data:
                user.email = form.email.data
                user.isComfirm = False
                emailsender = EmailSender.query.filter_by(fk_sid=user.id,fk_tid=user.fk_tid).first()
                emailsender.email=user.email
                db.session.add(emailsender)
            db.session.add(user)

            try:
                db.session.commit()
            except:
                db.session.rollback()
                flash('更新数据失败！')
        return redirect(url_for('main.profile'))
    form.name.data = current_user.name
    form.email.data = current_user.email
    return render_template('/changeProfile.html', form=form)


@main.route('/homework/changegroupid', methods=['GET'])
@login_required
def changegroupid():
    if current_user.perm == Permission.ADMIN:
        id = request.args['id']
        groupid = request.args['newgroup']
        if len(groupid) != 6:
            flash('群组长度不对，请确认为六位！')
            return 'fail'
        user = Students.query.filter_by(id=id).first()
        print(user.fk_tid)
        if user != None and user.fk_tid != groupid:
            user.fk_tid = groupid
            db.session.add(user)
            try:
                db.session.commit()
            except:
                db.rollback()
            flash('修改成功！')
            return 'ok'
        else:
            flash('修改失败(groupid)')
            return 'fail'


# 修改权限
@main.route('/homework/changeState', methods=['GET'])
@login_required
def changerState():
    if current_user.perm == Permission.ADMIN:
        id = request.values.get('id')
        perm = request.values.get('perm')
        if current_user.id != id:
            user = Students.query.filter_by(id=id).first()
            user.perm = int(perm)
            db.session.add(user)
            try:
                db.session.commit()
            except:
                db.session.rollback()
                flash('更新数据失败！')
            flash('修改权限成功!')
        else:
            flash('修改失败!')
    return redirect(url_for('main.manageuser'))


@main.route('/homework/confirmemail')
@login_required
def confirmemail():
    token = request.args['token']
    comfirm = current_user.confirm(token.encode())
    if comfirm:
        flash('验证成功！')
    else:
        flash('验证失败！')
    return redirect(url_for('main.profile'))


@main.route('/homework/deletecourses/<id>')
@login_required
def deletecourses(id):
    if current_user.is_admin():
        tid = current_user.fk_tid
        course = Courses.query.filter_by(id=id, fk_tid=tid).first()
        rmWorks = Houseworks.query.filter_by(fk_cid=id).all()
        if course is not None:
            db.session.delete(course)
            for i in rmWorks:
                picsave = PicSave.query.filter_by(fk_workid=i.id, fk_sid=current_user.id).all()
                for p in picsave:
                    os.remove(p.path)
                    db.session.delete(p)
                readhistory = ReadHistory.query.filter_by(fk_hid=i.id).all()
                for c in readhistory:
                    db.session.delete(c)
                db.session.delete(i)
            db.session.commit()
            flash('删除成功！')
        else:
            flash('操作失败！')
        return redirect(url_for('main.manage'))
    else:
        return render_template('/404.html'), 404


@main.route('/homework/delete/<id>')
@login_required
def deleteid(id):
    if current_user.is_admin():
        work = Houseworks.query.filter_by(id=int(id)).first()
        readhistory = ReadHistory.query.filter_by(fk_hid=int(id)).all()
        picsave = PicSave.query.filter_by(fk_workid=int(id), fk_sid=current_user.id).all()
        if work is not None:
            for p in picsave:
                os.remove(p.path)
                db.session.delete(p)
            for i in readhistory:
                db.session.delete(i)
            db.session.delete(work)
            db.session.commit()
            flash('删除成功！')
        else:
            flash('操作失败！')
        return redirect(url_for('main.manage'))
    else:
        return render_template('/404.html'), 404


# 删除用户
@main.route('/homework/deleteuser/<id>')
@login_required
def deleteiduser(id):
    if current_user.perm == Permission.ADMIN:
        user = Students.query.filter_by(id=id).first()
        emailsender = EmailSender.query.filter_by(fk_sid=id).all()
        readhistory = ReadHistory.query.filter_by(fk_hid=int(id)).all()
        if user is not None and current_user.id != id:
            for e in emailsender:
                db.session.delete(e)
            for r in readhistory:
                db.session.delete(r)
            db.session.delete(user)
            db.session.commit()
            flash('删除成功！')
        else:
            flash('操作失败！')
        return redirect(url_for('main.manageuser'))
    elif current_user.perm == 8:
        user = Students.query.filter_by(id=id).first()
        if user is not None and current_user.id != id and user.perm < current_user.perm and current_user.fk_tid == user.fk_tid:
            db.session.delete(user)

app/templates/addcourses.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}添加科目{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2 class="card-title ">添加科目</h2>
            {#  注册表格  #}
            <div class="col-md well well-lg">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
        <div class="row">
            <hr>
        </div>
    </div>
{% endblock %}

app/templates/addwork.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}添加作业{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2 class="card-title">添加作业</h2>
            {#  注册表格  #}
            <div class="col-md well well-lg">
                {{ wtf.quick_form(form) }}
            </div>

        </div>
        <div class="row">
            <hr>
        </div>

    </div>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/wangEditor.min.js') }}"></script>
    <script type="text/javascript">
        var $text1 = $('#content')
        $text1.hide()
        $text1.after("<div id='editor' class='form-group '></div>")
        var E = window.wangEditor
        var editor = new E('#editor')
        editor.customConfig.menus = [
            'head',  // 标题
            'bold',  // 粗体
            'fontSize',  // 字号
            'fontName',  // 字体
            'italic',  // 斜体
            'underline',  // 下划线
            'strikeThrough',  // 删除线
            'foreColor',  // 文字颜色
            'backColor',  // 背景颜色
            'link',  // 插入链接
            'list',  // 列表
            'justify',  // 对齐方式
            'quote',  // 引用
            'emoticon',  // 表情
            'image',  // 插入图片
            'video',  // 插入视频
            'code',  // 插入代码
            'undo',  // 撤销
            'redo'  // 重复
        ]
        editor.customConfig.uploadImgServer = '/homework/upload'
        editor.customConfig.uploadImgMaxSize = 3 * 1024 * 1024
        editor.create()
        document.getElementById('submit').addEventListener('click', function () {
            $text1.val(editor.txt.html())
        }, false)
    </script>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation" id="top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">首页</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ url_for('main.info') }}">作业信息</a>
                    </li>
                </ul>
                {% if current_user.is_authenticated and current_user.perm >=8 %}
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{{ url_for('main.manage' ) }}">管理作业</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{{ url_for('main.addWork' ) }}">添加作业</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{{ url_for('main.addCourses' ) }}">添加科目</a>
                        </li>
                    </ul>
                    {% if current_user.perm >= 8 %}
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="{{ url_for('main.manageuser' ) }}">管理账号</a>
                            </li>
                        </ul>
                    {% endif %}
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li>
                            <div class="btn-group ">
                                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                    菜单<span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu ">

                                    <li>
                                        <a class="dropdown-item " href="{{ url_for('main.profile') }}">个人信息</a>
                                    </li>
                                    <li><a class="dropdown-item " href="{{ url_for('main.changePassword' ) }}">修改密码</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{{ url_for('main.changeProfile') }}">修改信息</a>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li><a class="dropdown-item" href="{{ url_for('main.logout') }}">注销退出</a></li>
                                </ul>
                            </div>
                        </li>
                    {% else %}
                        <li>
                            <div class="btn-group ">
                                <a class="btn btn-success" href="{{ url_for('main.login') }}">登陆</a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        {# 提示信息#}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times</button>
                {{ message }}
            </div>
        {% endfor %}
        <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
        <script type="text/javascript">

            $(document).ready(function () {
                var topheight = $('#top').height()
                $(document).scroll(function (e) {
                    var x = $(document).scrollTop()
                    if (x > topheight && !$('#return_top').isShown) {
                        $('#return_top').show()
                    } else {
                        $('#return_top').hide()
                    }


                });
            });

        </script>
        <p id="return_top" style="display: none;"><a href="#top">return top</a></p>
    </div>
{% endblock %}
{% block content %}
    <div class="navbar center-block">
        <span class="label label-primary">友情链接</span>
        <div class="row ">
            <div class="col-xs-4 col-sm-4 text-center"><a class="btn-link " href="http://jw.jluzh.com/">吉林大学珠海学院教学平台</a>
            </div>
            <div class="col-xs-4 col-sm-4 text-center"><a class="btn-link" href="https://library.jluzh.com/">吉林大学珠海学院教学图书馆</a>
            </div>
            <div class="col-xs-4 col-sm-4 text-center"><a class="btn-link" href="http://www.jluzh.com//">吉林大学珠海学院官网</a>
            </div>
        </div>
        <p class="text-center text-info">版权所有Cendeal,保留一切权利<strong>粤ICP备18054828号</strong></p>
        <p class="text-center">
            <button type="button" class="badge badge-pill badge-success" data-toggle="modal"
                    data-target=".bs-adminwx-modal-sm">管理员微信
            </button>
            <button type="button" class="badge badge-pill badge-warning" data-toggle="modal"
                    data-target=".bs-thanks-modal-sm">点赞赏一下
            </button>
        </p>
        <!-- Small modal -->
        <div class="modal fade bs-adminwx-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-sm" role="document">

                <div class="modal-content">
                    <h5 class="modal-title text-center">扫一扫加微信
                        <a type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </h5>
                    <img src="{{ url_for('static',filename='adminwx.jpg') }}" style="max-width:100%;">
                </div>
            </div>
        </div>
        <div class="modal fade bs-thanks-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <h5 class="modal-title text-center">扫一扫赞赏
                        <a type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </h5>
                    <img src="{{ url_for('static',filename='thanks.jpg') }}" style="max-width:100%;">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/changePassword.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}修改密码{% endblock %}
{% block content %}
    <div class="container">
     <h2 class="card-title-4">修改密码</h2>
          <div class="page-header">
        </div>
        {#  表格  #}
        <div class="col-md-4 ">
            {{ wtf.quick_form(form) }}
        </div>
        <hr>
    </div>
{% endblock %}

app/templates/changeProfile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}修改个人信息{% endblock %}
{% block content %}
    <div class="container">
     <h2 class="card-title-4">修改个人信息</h2>
        {#  表格  #}
        <div class="col-md-4 ">
            {{ wtf.quick_form(form) }}
        </div>
    <hr>
    </div>
{% endblock %}

app/templates/editwork.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}修改作业{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2 class="card-title">修改作业</h2>
            {#  注册表格  #}
            <div class="col-md well well-lg">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
        <div class="row">
            <hr>
        </div>
    </div>
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/wangEditor.min.js') }}"></script>
    <script type="text/javascript">

        var $text1 = $('#content')
        $text1.hide()
        $text1.after('<div id=\'editor\' class=\'form-group\'></div>')
        $ed = $('#editor')
        var E = window.wangEditor
        var editor = new E('#editor')
        editor.customConfig.menus = [
            'head',  // 标题
            'bold',  // 粗体
            'fontSize',  // 字号
            'fontName',  // 字体
            'italic',  // 斜体
            'underline',  // 下划线
            'strikeThrough',  // 删除线
            'foreColor',  // 文字颜色
            'backColor',  // 背景颜色
            'link',  // 插入链接
            'list',  // 列表
            'justify',  // 对齐方式
            'quote',  // 引用
            'emoticon',  // 表情
            'image',  // 插入图片
            'video',  // 插入视频
            'code',  // 插入代码
            'undo',  // 撤销
            'redo'  // 重复
        ]
        $ed.html('{{ content|safe }}')
        editor.customConfig.uploadImgServer = '/homework/upload'
        editor.customConfig.uploadImgMaxSize = 3 * 1024 * 1024
        editor.create()
        // 初始化 textarea 的值
        document.getElementById('submit').addEventListener('click', function () {
            $text1.val(editor.txt.html())
        }, false)
    </script>
{% endblock %}

app/templates/info.html
{% extends "/base.html" %}
{% block content %}

    <div class="container">
        <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
        <h2 class="card-title-4">作业通知
            <small>[{{ num }}]

            </small>
        </h2>
        <div id="accordion">
            {#      类型#}
            {% for i in dict_for_course %}
                <div class="card">
                    <div class="card-header" id="headingOne{{ i['id'] }}">
                        <h5 class="card-title">
                            <button class="list-group-item " data-toggle="collapse"
                                    data-target="#collapseOne{{ i['id'] }}" aria-expanded="true"
                                    aria-controls="collapseOne{{ i['id'] }}">
                                {{ i['name'] }}<small>[{{ i['len'] }}]</small>
                                <span class="caret"></span>
                                {% if i['len']-i['read'][1]>0 %}
                                <span class="badge badge-success" data-toggle="tooltip" data-placement="top" title="未读">未读{{ i['len']-i['read'][1] }}</span>
                                {% endif %}

                            </button>
                        </h5>
                    </div>
                    <div id="collapseOne{{ i['id'] }}" class="collapse  " aria-labelledby="headingOne{{ i['id'] }}"
                         data-parent="#accordion">
                        {% for j in i['list'] %}
                            {% if j.state !=2 %}
                                <div class="media">
                                        <div class="media-left">
                                            <a class="btn btn-success  disabled ">{{ j.title[0]|upper }}</a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading"><strong>{{ j.title }}</strong><small>[{{ j.createdate}}]</small>
                                                {% if j not in i['read'][0] %}
                                                 <small><span class="badge badge-success" style="float: left">未读</span></small>
                                                     <a class="btn btn-sm btn-warning" style="float: right" href="{{ url_for('main.read',infoid=j.id,isread=False) }}">查看</a>
                                                    {% else %}
                                                 <small><span class="badge badge-secondary" style="float: left">已读</span></small>
                                                     <a class="btn btn-sm btn-warning" style="float: right" href="{{ url_for('main.read',infoid=j.id,isread=True) }}">查看</a>
                                                {% endif %}

                                            </h4>
                                            <p style="color: darkgray">{{ j.content[:20]|striptags }}...</p>
                                        </div>
                                <hr>
                                </div>

                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}登陆{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="card-title-4">登陆</h2>
        {#  登陆表格  #}
        <div class="col-md-4 ">
            {{ wtf.quick_form(form) }}
        </div>
            <hr>
        <p>
            新用户？
            <a class="btn bg-primary" href="{{ url_for('main.register') }}">
                点击注册
            </a>
        </p>
    </div>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h2 class="card-title-4">首页</h2>
        <div class="jumbotron">
            <h1 class="display-4">作业布置</h1>
            <p class="lead">Homework Online,这是一个用于学生记录作业任务的网站。如果要申请作为班级管理权限，请添加网站管理员微信</p>
            <hr class="my-4">
            <p>吉林大学珠海学院 计算机学院 软件工程</p>
            <p class="lead">
                <a class="btn btn-success btn-lg" href="{{  url_for('main.info')}}" role="button">查看作业信息</a>
            </p>
        </div>
    </div>
     {{ super() }}
{% endblock %}

app/templates/managegroup.html
<body>{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}管理群组{% endblock %}
{% block content %}
    <div class="container">
       <table class="table  table-bordered "  >
       <h2 class="card-title">管理群组
       <div class="input-group col-lg-6 " style="float: right">
                    <input type="text" id='inputdata' class="form-control" {% if id == None %} placeholder="通过 学号 搜索..."
                           {% else %}value="{{ id }}" {% endif %}>
                    <span class="input-group-btn">
                    <button id='searchbtn' class="btn btn-primary" type="button">Go!</button>
                      <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
                      <script type="text/javascript">
                          $('#searchbtn').click(function () {
                              location.href = '/homework/search?id=' + $('#inputdata').val()
                          })
                      </script>
                    </span>
                </div><!-- /input-group -->
       </h2>
         {% if userlist == None %}
                <p>无记录！</p>
            {% else %}
            <thead>
            <tr>
                <th scope="col">学号</th>
                <th scope="col">姓名</th>
                <th scope="col">类型</th>
                <th scope="col">邮箱</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for i in userlist %}
                <tr>
                    <th scope="row">{{ i.id }}</th>
                    <td>{{ i.name }}</td>
                    <td>
                        <div class="btn-group">
                            {% if i.perm==8 %}
                                <label class="label label-warning" >学&nbsp;&nbsp;&nbsp;&nbsp;委
                            {% elif i.perm==16%}
                                <label class="label label-primary">管理员
                            {% else %}
                                <label class="label label-success">普&nbsp;&nbsp;&nbsp;&nbsp;通
                            {% endif %}
                            </label>

                        </div>
                    </td>
                    <td>{{ i.email }}
                        {% if i.isComfirm %} <span class="label label-success">已验证</span>
                        {% else %}
                            <span class="label label-warning">未验证</span>
                        {% endif %}
                    </td>
                    <td><a class="btn btn-danger btn-sm" data-toggle="modal" data-target="#ModalCenter{{ i.id }}">删除</a>
                    </td>
                    <div class="modal fade" id="ModalCenter{{ i.id }}" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">操作提示</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    确定删除
                                    <button class="btn btn-warning">{{ i.id }}</button>
                                    吗？
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                                    <a href="/homework/deleteuser/{{ i.id }}" type="button" class="btn btn-primary">确定</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    </h5>
                </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}注册{% endblock %}
{% block content %}
    <div class="container">
     <h2 class="card-title-4">注册</h2>
        {#  注册表格  #}
        <div class="col-md-4 ">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}